# Если хочешь поддержать проект — ссылки ниже.
# Раскомментируй те платформы где у тебя есть аккаунт.

# github: [IgorShutko]
# patreon: igorshutko
# buy_me_a_coffee: igorshutko
custom: ["https://www.targetplus-agency.com/?utm_source=github&utm_medium=funding&utm_campaign=horoshop-skill", "https://t.me/shutko_ads"]
